// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: order.proto

package order

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderCreater_Create_FullMethodName = "/calculator.OrderCreater/Create"
	OrderCreater_Status_FullMethodName = "/calculator.OrderCreater/Status"
)

// OrderCreaterClient is the client API for OrderCreater service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderCreaterClient interface {
	Create(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderResponse, error)
	Status(ctx context.Context, in *OrderID, opts ...grpc.CallOption) (*OrderStatus, error)
}

type orderCreaterClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderCreaterClient(cc grpc.ClientConnInterface) OrderCreaterClient {
	return &orderCreaterClient{cc}
}

func (c *orderCreaterClient) Create(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderResponse)
	err := c.cc.Invoke(ctx, OrderCreater_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderCreaterClient) Status(ctx context.Context, in *OrderID, opts ...grpc.CallOption) (*OrderStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderStatus)
	err := c.cc.Invoke(ctx, OrderCreater_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderCreaterServer is the server API for OrderCreater service.
// All implementations must embed UnimplementedOrderCreaterServer
// for forward compatibility.
type OrderCreaterServer interface {
	Create(context.Context, *OrderRequest) (*OrderResponse, error)
	Status(context.Context, *OrderID) (*OrderStatus, error)
	mustEmbedUnimplementedOrderCreaterServer()
}

// UnimplementedOrderCreaterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderCreaterServer struct{}

func (UnimplementedOrderCreaterServer) Create(context.Context, *OrderRequest) (*OrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedOrderCreaterServer) Status(context.Context, *OrderID) (*OrderStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedOrderCreaterServer) mustEmbedUnimplementedOrderCreaterServer() {}
func (UnimplementedOrderCreaterServer) testEmbeddedByValue()                      {}

// UnsafeOrderCreaterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderCreaterServer will
// result in compilation errors.
type UnsafeOrderCreaterServer interface {
	mustEmbedUnimplementedOrderCreaterServer()
}

func RegisterOrderCreaterServer(s grpc.ServiceRegistrar, srv OrderCreaterServer) {
	// If the following call pancis, it indicates UnimplementedOrderCreaterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderCreater_ServiceDesc, srv)
}

func _OrderCreater_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderCreaterServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderCreater_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderCreaterServer).Create(ctx, req.(*OrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderCreater_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderCreaterServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderCreater_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderCreaterServer).Status(ctx, req.(*OrderID))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderCreater_ServiceDesc is the grpc.ServiceDesc for OrderCreater service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderCreater_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.OrderCreater",
	HandlerType: (*OrderCreaterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _OrderCreater_Create_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _OrderCreater_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
