// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: restaurant.proto

package restaurant

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProcessCreater_Create_FullMethodName = "/restaurant.ProcessCreater/Create"
	ProcessCreater_Status_FullMethodName = "/restaurant.ProcessCreater/Status"
)

// ProcessCreaterClient is the client API for ProcessCreater service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProcessCreaterClient interface {
	Create(ctx context.Context, in *OrderDetails, opts ...grpc.CallOption) (*OrderStatus, error)
	Status(ctx context.Context, in *OrderID, opts ...grpc.CallOption) (*OrderStatus, error)
}

type processCreaterClient struct {
	cc grpc.ClientConnInterface
}

func NewProcessCreaterClient(cc grpc.ClientConnInterface) ProcessCreaterClient {
	return &processCreaterClient{cc}
}

func (c *processCreaterClient) Create(ctx context.Context, in *OrderDetails, opts ...grpc.CallOption) (*OrderStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderStatus)
	err := c.cc.Invoke(ctx, ProcessCreater_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processCreaterClient) Status(ctx context.Context, in *OrderID, opts ...grpc.CallOption) (*OrderStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderStatus)
	err := c.cc.Invoke(ctx, ProcessCreater_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProcessCreaterServer is the server API for ProcessCreater service.
// All implementations must embed UnimplementedProcessCreaterServer
// for forward compatibility.
type ProcessCreaterServer interface {
	Create(context.Context, *OrderDetails) (*OrderStatus, error)
	Status(context.Context, *OrderID) (*OrderStatus, error)
	mustEmbedUnimplementedProcessCreaterServer()
}

// UnimplementedProcessCreaterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProcessCreaterServer struct{}

func (UnimplementedProcessCreaterServer) Create(context.Context, *OrderDetails) (*OrderStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedProcessCreaterServer) Status(context.Context, *OrderID) (*OrderStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedProcessCreaterServer) mustEmbedUnimplementedProcessCreaterServer() {}
func (UnimplementedProcessCreaterServer) testEmbeddedByValue()                        {}

// UnsafeProcessCreaterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProcessCreaterServer will
// result in compilation errors.
type UnsafeProcessCreaterServer interface {
	mustEmbedUnimplementedProcessCreaterServer()
}

func RegisterProcessCreaterServer(s grpc.ServiceRegistrar, srv ProcessCreaterServer) {
	// If the following call pancis, it indicates UnimplementedProcessCreaterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProcessCreater_ServiceDesc, srv)
}

func _ProcessCreater_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessCreaterServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessCreater_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessCreaterServer).Create(ctx, req.(*OrderDetails))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessCreater_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessCreaterServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessCreater_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessCreaterServer).Status(ctx, req.(*OrderID))
	}
	return interceptor(ctx, in, info, handler)
}

// ProcessCreater_ServiceDesc is the grpc.ServiceDesc for ProcessCreater service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProcessCreater_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "restaurant.ProcessCreater",
	HandlerType: (*ProcessCreaterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ProcessCreater_Create_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _ProcessCreater_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "restaurant.proto",
}
